org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configureondemand=true

mod_name=Mint
mod_id=mint
mod_version=1.2.0
mod_group=me.bewf
archives_base_name=mint

minecraft_version=1.8.9
loader_version=0.19.5

feather_build=2
osl_version=0.21.0

oneconfig_version=1.2.13

compose_version=1.12.1
skiko_version=0.999.6
coroutines_version=1.10.2

devauth_version=1.2.2
