pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe (snapshots)'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		gradlePluginPortal()
		mavenCentral()
	}
}

rootProject.name = mod_id
